spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/todolistdb
    username: sally
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  liquibase:
    change-log: classpath:liquibase/changelog/todolistdb.change-master.xml
    enabled: true